### ISSUE TITLE
Trace ends with C stack trace/core dump

### ISSUE THREAD

**Issue by JesseBowling** [buffer/thug#110]
[2015-01-09 14:37:26] [HTTP] URL: http://maps.gstatic.com/maps-api-v3/api/js/19/5/util.js (Content-type: text/javascript, MD5: b20c06e1279f94ac163dca27b5c9aea7)

#
# Fatal error in ../src/runtime.cc, line 778
# CHECK(V8::ArrayBufferAllocator() != NULL) failed
#

==== C stack trace ===============================

 1: v8::internal::Runtime::SetupArrayBufferAllocatingData(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSArrayBuffer>, unsigned long, bool)
 2: v8::internal::Runtime_ArrayBufferInitialize(int, v8::internal::Object**, v8::internal::Isolate*)
 3: ??
Trace/breakpoint trap (core dumped)

So this looks to be within V8 itself, and perhaps belongs there, but unsure of what exactly is wrong. What can I do to help/get this to the right place?

**Comment by buffer** [comment]
Seems like you are right. In order to understand more about what is happening you can run thug in a debugged environment i.e. using gdb. Just run "gdb python" and then "run thug.py [options]". This woul allow you to inspect the stack and understand what is causing the issue. By the way the greatest issue is that PyV8 is not maintained from months now and it uses a specific version of V8 so upgrading (thus potentially solving the issue) could be impossible right now. Already thinking about a solution for that but it's not something that will happen in short time unfortunately.

**Comment by buffer** [comment]
The issue should be now fixed by using my pyv8 fork (available at https://github.com/buffer/pyv8). I am going to update the documentation because right now installing V8/PyV(8 is simpler. Following the procedure

1.Checkout V8 source code from SVN
$ svn checkout http://v8.googlecode.com/svn/trunk/ v8

2. Checkout PyV8 source code from GIT
$ git clone https://github.com/buffer/pyv8.git

3. Set the environment variable V8_HOME with the V8 source code absolute path (you need to change the value reported below)
$ export V8_HOME=/home/buffer/v8

4.  Move to PyV8 source code directory
$ cd pyv8

5. Build and install (PyV8 setup.py will properly install both V8 and PyV8)
~/pyv8 $ python setup.py build
~/pyv8 $ sudo python setup.py install

Please let me know if it works fine as here.
