### ISSUE TITLE
Dead loop in function setTimeout

### ISSUE THREAD

**Issue by l547116382** [buffer/thug#120]
HI,
when i run a sample has the javascript code 
				function change_img(){
                                        ........
					tt=setTimeout('change_img()',4000);
				}
thug enter dead loop.

I modify the code in function setTimeout() to limit exectuion 
        self.settimeout_exec_counts += 1
        if self.settimeout_exec_counts < self.MAX_EXEC_COUNTS:
            if log.ThugOpts.delay:
                delay = min(delay, log.ThugOpts.delay)
                timer = Window.Timer(self, f, delay, False, lang)
                self.timers.append(timer)
                timer.start()
        self.settimeout_exec_counts -= 1
        return len(self.timers) - 1

Thank you for your work.

**Comment by buffer** [comment]
This is not a bug since your code is just looping calling again and again the same function. A real browser would behave like Thug so why should we enforce a maximum number of loops thus potentially giving to someone the opportunity to easily evade the analysis (loop N times and start doing something at N+1th round when Thug is not detecting it)?
