### ISSUE TITLE
Recursive redirect processing until analysis timeout or threshold reached

### ISSUE THREAD

**Issue by wojtossfm** [buffer/thug#127]
The following sample page causes Thug to recursively continue processing till the timeout as far as I can tell:

```
<html>
<body>
<script>
try{
        //Refresh
        function _refreshPage(){
                var i=new Image();
                function do_load(){window.location=window.location}
                function do_error(){setTimeout(_refreshPage,60000)}
                i.onload=do_load;
                i.onerror=do_error;
                i.src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAAAAAA6fptVAAAACklEQVR4nGP6DwABBQECz6AuzQAAAABJRU5ErkJggg==";
        }
        setTimeout(_refreshPage,5000);
}catch(ex){

}
try {
    //Refresh
    setTimeout(function() {
        document.location.href = "/test.html?refresh_ce";
    }, 300000);
} catch (ex) {}
try {
    //Refresh
    setTimeout(function() {
        document.location.href = "/test.html?refresh_ce";
    }, 300000);
} catch (ex) {}
</script>
</body>
</html>
```

Reproduction steps:
```
# Save the test.html in the current folder
python -m SimpleHTTPServer &
time python /opt/thug/src/thug.py -F -M --timeout=600 --delay=100 --verbose http://localhost:8000/test.html
# logs...

# Watch Thug chase its own tail?
# Thug finishes analyzing only when the timeout is reached
real    10m13.069s
user    7m30.972s
sys    0m3.612s
```

I'm not sure whether to list this as a bug or a feature request. I expected Thug to maintain some notion of visited pages and to skip revisiting of paths that were already visited. Let me know if you have trouble reproducing this, but the above example should suffice. This was observed with version 0.6.2, but as far as I looked through the commits I didn't see any changes between it and 0.6.3 that would impact this.

**Comment by buffer** [comment]
First of all thanks for your really detailed report. I can reproduce the behavior you are describing. Well in theory a real browser would behave the way Thug behaves and would keep looping until some kind of browser-defined timeout is fired. Keeping track of the already visited pages and skipping them is dangerous since it exposes to evasion (i.e. loop 2 times on the same URL and the second time change the content served and Thug is evaded). The timeout option was added long time ago so that the analyst could enforce a timeout like a real browser would do. But choosing a default value > 0 is not that simple. This the reason why I opted for no timeout at all by default and let each one decide for a specific value which fits his needs.

**Comment by wojtossfm** [comment]
So I understand that this is a won't fix and working as intended. Not sure when I'll have the time but would you be interested in a pull request adding a url visit limit as an optional feature?

**Comment by buffer** [comment]
I would be really interested in such feature if optionally available to the end user so yes I would be interested in such pull request so feel free to submit. I closed the issue since Thug is working as intended right now so this is not a real issue. Thanks!
