### ISSUE TITLE
Feature Request: New test option/script to check completeness and functionality of Thug installation

### ISSUE THREAD

**Issue by aikinci** [buffer/thug#134]
Recently after Androguard analysis has been added to thug and I don't use thug for mobile malware analysis the warning messages start to get ugly for each analysis I run. Furthermore I don't know of a way to determine if my thug installation is the way it is expected to be like the right libraries/additional programs etc. 

Therefore I suggest that we write a small script/or new option for thug to check the full capabilities and problems regarding the current installation together with the installed library versions. This could also prove very useful in debugging and during issue creation.

Thanks for your continued and valuable contribution to the community.

Regards

**Comment by buffer** [comment]
Ali,
the warning messages are generated just for dependencies marked as optional. Not having a required package would cause Thug to crash. Not showing a warning message is not advisable IMHO because you would never know you failed to install Androguard in such case. Even if you really need it. We could think about an additional option for not showing just such warnings (keeping showing the warnings as default) if you think it's worth doing.

**Comment by aikinci** [comment]
The real problem for me is Thug is using many different libraries and external components. Those may have varing versions and when I use Thug I can not be completely certain that the results I am getting are the expected results. So a simple install check might be useful. I could maybe write one which could sit in the tools directoy if you agree.

By the way thanks for Thug and your great work. I really appreciate it.

**Comment by buffer** [comment]
Ali,
I would be really glad seeing this tool in the utils directory so please go for it. Please let me know if you need any kind of help/support. 

Thanks!
