### ISSUE TITLE
Update MongoDB schema to match code with behaviour.

### ISSUE THREAD

**Issue by standa4** [buffer/thug#203]
Hello,
would be possible to update the logging capabilities so that the code snippet could be matched with behaviour?
In MongoDB.py there are two funcions add_code_snippet and add_behavior but it is not possible to match behaviour with the code snippet and with many code snippets it is almost impossible to determine what code caused the behaviour event.
Thank you.

**Comment by buffer** [comment]
FYI I committed the first changes in the dev branch (https://github.com/buffer/thug/tree/dev). Basically add_code_snippet now creates a tag id for each code snippet and the method returns it so that add_behavior/add_behavior_warn can be passed this additional (and optional) parameter thus storing it in the behavior entry. I moved all the shellcode-related stuff to this new approach and it seems like it works fine. I will keep on migrating existing code in the next days. BTW migrating to the new approach is a trivial operation so feel free to submit PR if something you need requires immediate care.

**Comment by kira0204** [comment]
Hello, would we be moving forward with this?

**Comment by buffer** [comment]
I think there's still little to do with regards to this issue but I will take a look at it in the next days (quite busy in the last days). If you want to take care of it, please feel free to do! Thanks!
